jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - run: git clone https://github.com/vinagreti/alientec ./
      - run: npm i
      - run: npm run test
      - run: npm run e2e
      - run: npm run build.prod
